global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus&u=influxdb&p=influxdb.123"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus&u=influxdb&p=influxdb.123"

alerting:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: "node"
    file_sd_configs:
      - files: 
        - /etc/prometheus/file_sd/node.yaml
    # static_configs:
    #   - targets:
    #       - 172.0.0.1:9100
  - job_name: "mysql"
    file_sd_configs:
      - files: 
        - /etc/prometheus/file_sd/mysql.yaml
